Fix GInitiallyUnowned marshalling from native
TestFloating.cs(36,14): error CS0266: Cannot implicitly convert type 'GLib.Object' to 'GLib.InitiallyUnowned'. An explicit conversion exists (are you missing a cast?)