Fix case with Unref and Ref added twice
bindinate seems to duplicate Ref and Unref methods for some objects
Handle this special case by ignoring

TestFundamentalObject.cs(80,24): error CS0111: Type 'TestFundamentalObject' already defines a member called 'regress_test_fundamental_object_ref' with the same parameter types
TestFundamentalObject.cs(91,22): error CS0111: Type 'TestFundamentalObject' already defines a member called 'regress_test_fundamental_object_unref' with the same parameter types