Fix unsigned enum generation
TestEnumUnsigned.cs(14,12,14,22): error CS0266: Cannot implicitly
convert type 'uint' to 'int'. An explicit conversion exists (are you
missing a cast?)